logging:
  level:
    ROOT: INFO

server:
  port: 8932
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: MysqlDemo
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xydb?characterEncoding=UTF-8&autoReconnect=true&useSSL=false